[package]
name = "zk_coinjoin_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bellman = "0.8"  # For zk-SNARKs
rand = "0.8"     # For random number generation
serde = { version = "1.0", features = ["derive"] }  # For serialization
