[package]
name = "zk_coinjoin_lib"
version = "0.1.0"
edition = "2021"
description = "ZK Proof library for Coinjoin"
homepage = "https://arealayer.net/projects"
repository = "https://github.com/arealayer/zk_coinjoin_lib"
license = "MIT"

[dependencies]
bellman = "0.14"
rand = "0.8"     
bitcoin = "0.32.3"
reqwest = "0.12.7"
pairing = "0.23.0"
serde =  { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"